server:
  tomcat:
    max-threads: 700
    uri-encoding: UTF-8
  compression:
    enabled: true
    mime-types: application/json,application/javascript,text/html,text/xml,text/plain,text/css
  port: 12345

spring:
    jmx:
        enabled: false

javafx:
    title: MyCoolApp
    stage:
        resizable: true