server:
  tomcat:
    max-threads: 700
    uri-encoding: UTF-8
  compression:
    enabled: true
    mime-types: application/json,application/javascript,text/html,text/xml,text/plain,text/css
  port: 12345

spring:
  data:
    mongodb:
      host: 192.168.0.148
      database: blog_mongo